import type { StockItem } from "@/features/materials";

const NOW = "2026-05-21T12:00:00.000Z";

/** Catalogue serrurerie injecté via `seedCompanyStockCatalog` (onboarding stock vide). */
export const LOCKSMITH_STOCK_SEED_CATALOG: Omit<StockItem, "companyId">[] = [
  {
    id: "seed-stock-cyl-sec",
    reference: "CYL-EURO-80",
    lecotSku: "LEC-CYL-2012",
    description: "Cylindre européen 80 mm sécurité",
    quantity: 0,
    alertThreshold: 4,
    unit: "pcs",
    updatedAt: NOW,
  },
  {
    id: "seed-stock-cyl-70",
    reference: "CYL-EURO-70",
    lecotSku: "LEC-CYL-2008",
    description: "Cylindre européen 70 mm",
    quantity: 2,
    alertThreshold: 6,
    unit: "pcs",
    updatedAt: NOW,
  },
  {
    id: "seed-stock-barillet",
    reference: "BAR-A2P",
    lecotSku: "LEC-CYL-2013",
    description: "Barillet A2P 5 goupilles",
    quantity: 0,
    alertThreshold: 3,
    unit: "pcs",
    updatedAt: NOW,
  },
  {
    id: "seed-stock-cremone",
    reference: "CREM-3PT",
    lecotSku: "LEC-SER-1001",
    description: "Crémone multipoint 3 points",
    quantity: 1,
    alertThreshold: 4,
    unit: "pcs",
    updatedAt: NOW,
  },
  {
    id: "seed-stock-gache",
    reference: "GACH-ELEC",
    lecotSku: "LEC-CTL-4003",
    description: "Gâche électrique réversible",
    quantity: 3,
    alertThreshold: 8,
    unit: "pcs",
    updatedAt: NOW,
  },
  {
    id: "seed-stock-serrure",
    reference: "SERR-APL",
    lecotSku: "LEC-SER-1014",
    description: "Serrure applique A2P",
    quantity: 5,
    alertThreshold: 6,
    unit: "pcs",
    updatedAt: NOW,
  },
  {
    id: "seed-stock-cle-badge",
    reference: "BADGE-125",
    lecotSku: "LEC-CTL-4024",
    description: "Badge RFID 125 kHz",
    quantity: 12,
    alertThreshold: 20,
    unit: "pcs",
    updatedAt: NOW,
  },
  {
    id: "seed-stock-telecommande",
    reference: "TELE-4CH",
    lecotSku: "LEC-CTL-4048",
    description: "Télécommande portail 4 canaux",
    quantity: 0,
    alertThreshold: 5,
    unit: "pcs",
    updatedAt: NOW,
  },
  {
    id: "seed-stock-vis",
    reference: "VIS-INOX-6",
    lecotSku: "LEC-CNS-6051",
    description: "Vis inox M6 × 40 (boîte 100)",
    quantity: 8,
    alertThreshold: 15,
    unit: "boîte",
    updatedAt: NOW,
  },
  {
    id: "seed-stock-gond",
    reference: "GOND-REN",
    lecotSku: "LEC-QUI-3060",
    description: "Gond renforcé paumelle lourde",
    quantity: 14,
    alertThreshold: 10,
    unit: "pcs",
    updatedAt: NOW,
  },
  {
    id: "seed-stock-joint",
    reference: "JOINT-EPDM",
    lecotSku: "LEC-QUI-3042",
    description: "Joint EPDM porte blindée",
    quantity: 4,
    alertThreshold: 12,
    unit: "m",
    updatedAt: NOW,
  },
  {
    id: "seed-stock-lubrif",
    reference: "LUB-CYL",
    lecotSku: "LEC-CNS-6037",
    description: "Lubrifiant cylindre 400 ml",
    quantity: 6,
    alertThreshold: 8,
    unit: "pcs",
    updatedAt: NOW,
  },
  {
    id: "seed-stock-gants",
    reference: "GANT-NIT",
    lecotSku: "LEC-OUT-7044",
    description: "Gants nitrile (boîte 100)",
    quantity: 22,
    alertThreshold: 10,
    unit: "boîte",
    updatedAt: NOW,
  },
  {
    id: "seed-stock-lecot",
    reference: "LECOT-POIG",
    lecotSku: "LEC-QUI-3001",
    description: "Poignée de porte Lecot inox",
    quantity: 7,
    alertThreshold: 10,
    unit: "pcs",
    updatedAt: NOW,
  },
];

/** Références catalogue pour résolution d'images produit (overlay Lecot). */
export function locksmithStockCatalogRows(): StockItem[] {
  return LOCKSMITH_STOCK_SEED_CATALOG.map((row) => ({ ...row, companyId: "" }));
}
