/** Labels UI affichés pendant l'exécution des outils chatbot (stream SSE). */
export const CHATBOT_TOOL_LABELS: Record<string, string> = {
  get_workspace_summary: "Vue d'ensemble",
  list_interventions: "Interventions",
  get_intervention_detail: "Détails dossier",
  search_workspace: "Recherche",
  list_clients: "Clients",
  get_client_detail: "Fiche client",
  list_quotes: "Devis",
  list_technicians: "Techniciens",
  list_stock_alerts: "Stock",
  list_material_orders: "Commandes matériel",
  list_inbox_notifications: "Inbox",
  list_gmail_inbox: "Gmail — boîte",
  get_gmail_message: "Gmail — lecture",
  suggest_gmail_intervention_links: "Gmail — dossiers suggérés",
  send_gmail_reply: "Gmail — réponse",
  link_gmail_to_intervention: "Gmail — lien dossier",
  list_intervention_emails: "Emails dossier",
  get_intervention_billing: "Facturation",
  list_portal_chat: "Chat portail",
  get_technician_planning: "Planning technicien",
  statistiques_periode: "Statistiques",
  create_intervention: "Création dossier",
  update_intervention_status: "Mise à jour statut",
  assign_technician: "Assignation technicien",
  update_intervention_schedule: "Planification",
  add_timeline_comment: "Note interne",
  save_client_email: "Email client",
  send_intervention_email: "Envoi email",
  focus_intervention_document: "PDF PWA",
  patch_intervention_billing: "Facturation",
  update_intervention_billing: "Facturation",
  search_lecot_products: "Catalogue Lecot",
  list_supplier_orders: "Commandes fournisseur",
  order_lecot_parts: "Commande Lecot",
  list_company_material_orders: "Bons matériel société",
  approve_material_orders: "Validation demandes matériel",
  focus_stock_item: "Focus stock",
  focus_billing_case: "Focus facturation",
  open_crm_dossier: "Ouvrir dossier",
  trigger_accounting_export: "Export comptable CSV",
  trigger_payroll_export: "Export feuilles de temps",
  list_vehicle_stock: "Stock véhicule",
  add_vehicle_stock_item: "Ajout stock véhicule",
  update_vehicle_stock_item: "Mise à jour stock véhicule",
  diagnose_equipment_photo: "Diagnostic IA photo",
  parse_voice_job_closure: "Clôture vocale IA",
  get_contract_churn_risks: "Risque résiliation contrats",
};
